# see https://github.com/ogrisel/python-appveyor-demo

skip_non_tags: true

environment:
  global:

    KOMBILO_VERSION: "081"

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      ARCHITECTURE: "win32-2.7"
      VCOMP90_PATH: "x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.21022.8_none_ecdf8c290e547f39"
      MSVCx90_PATH: "x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_5094ca96bcb6b2bb"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      ARCHITECTURE: "win-amd64-2.7"
      VCOMP90_PATH: "amd64_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.21022.8_none_a5325551f9d85633"
      MSVCx90_PATH: "amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.8387_none_08e793bfa83a89b5"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project.
  - "%CMD_IN_ENV% pip install wheel Babel"

build_script:
  # in kombilo folder, license.rst exists only as a symlink, so need to copy the
  # real file to that location to be able to use it
  - "%CMD_IN_ENV% cp license.rst kombilo"

  # compile mo files
  - "%CMD_IN_ENV% pybabel compile -d kombilo/lang -D kombilo"

  # copy dlls which we want to include in the wheel
  - ps: "ls c:/windows/winsxs/amd64_microsoft.vc90.crt*"
  - "cp c:/windows/winsxs/%MSVCx90_PATH%/ms*90.dll c:/projects/kombilo/kombilo/"
  - "cp c:/windows/winsxs/Manifests/%MSVCx90_PATH%.manifest c:/projects/kombilo/kombilo/Microsoft.VC90.CRT.manifest"

  - "cp c:/windows/winsxs/%VCOMP90_PATH%/vcomp90.dll c:/projects/kombilo/kombilo/"
  - "cp c:/windows/winsxs/Manifests/%VCOMP90_PATH%.manifest c:/projects/kombilo/kombilo/Microsoft.VC90.OpenMP.manifest"

  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python setup.py bdist_wheel"

artifacts:
  - path: dist\*.*

