# see https://github.com/ogrisel/python-appveyor-demo

skip_non_tags: true

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      VCOMP90_PATH: "x86_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.21022.8_none_ecdf8c290e547f39"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      VCOMP90_PATH: "amd64_microsoft.vc90.openmp_1fc8b3b9a1e18e3b_9.0.21022.8_none_a5325551f9d85633"

install:
  - "cinst innosetup"

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project.
  - "%CMD_IN_ENV% pip install -r requirements.txt"
  - "%CMD_IN_ENV% pip install wheel"
  - "%CMD_IN_ENV% pip install PyInstaller==3.1.1"
  # note: 3.2 is broken, see https://github.com/pyinstaller/pyinstaller/issues/1974

build_script:
  # in kombilo folder, license.rst exists only as a symlink, so need to copy the
  # real file to that location to be able to use it
  - "%CMD_IN_ENV% cp license.rst kombilo"

  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python setup.py bdist_wheel"  # note: the wheel also requires the dlls, notably vvcomp90.dll, which is not easily found automatically(?)

  - "%CMD_IN_ENV% cp build\\lib.win32-2.7\\kombilo\\_libkombilo.pyd kombilo"
  - "%CMD_IN_ENV% pyinstaller.exe --windowed kombilo.spec"

  # pyinstaller does not find vcomp90.dll by itself :-(
  - ps: "cp c:/windows/winsxs/%VCOMP90_PATH%/vcomp90.dll c:/projects/kombilo/dist/kombilo/"
  - ps: "cp c:/windows/winsxs/Manifests/%VCOMP90_PATH%.vc90.openmp_1fc8b3b9a1e18e3b_9.0.21022.8_none_ecdf8c290e547f39.manifest c:/projects/kombilo/dist/kombilo/Microsoft.VC90.OpenMP.manifest"


  - ps: "cp c:/projects/kombilo/kombilo.ico c:/projects/kombilo/dist/kombilo"
  - ps: "ls c:/projects/kombilo/dist/kombilo"

  - "%CMD_IN_ENV% \"C:\\Program Files (x86)\\Inno Setup 5\\iscc.exe\" kombilo.iss"

artifacts:
  - path: dist\*.*
  - path: installer\*

